services:
  python:
    image: python:3.11-slim
    build:
      context: .
      dockerfile: calories_tracker_dockerfile
    container_name: calories_tracker
    command: python3 -m diet_tracker.bot
    volumes:
      - ../:/app
      - ../data/:/data
    env_file:
      - .env  # Contains telegram token
    working_dir: /app

volumes:
  venv:
